apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: video-streaming-platform-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AbstractLK/video-streaming-platform.git
    targetRevision: main
    path: helm/apps/video-streaming-platform
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

