apiVersion: v1
kind: ServiceAccount
metadata:
  name: upload-processing-sa
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.irsa.uploadProcessingRoleArn | quote }}
  labels:
    {{- include "vsp.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: streaming-sa
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.irsa.streamingRoleArn | quote }}
  labels:
    {{- include "vsp.labels" . | nindent 4 }}

