pipeline {
  agent any

  environment {
    AWS_REGION = credentials('aws-region')
    AWS_ACCOUNT_ID = credentials('aws-account-id')
    ECR_REGISTRY = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
    FRONTEND_BUCKET = credentials('frontend-bucket')
    CLOUDFRONT_DISTRIBUTION_ID = credentials('frontend-cloudfront-distribution-id')
    IMAGE_TAG = "${env.BUILD_NUMBER}-${env.GIT_COMMIT.take(7)}"
    DEPLOY_BRANCH = 'main'
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Decide Build') {
      steps {
        script {
          def lastMessage = sh(script: 'git log -1 --pretty=%B', returnStdout: true).trim()
          def changedFiles = sh(script: 'git diff --name-only HEAD~1 HEAD || true', returnStdout: true).trim()

          def isJenkinsDeployCommit = lastMessage.startsWith('chore: deploy images')
          def hasSourceChanges = changedFiles
            .split('\\n')
            .any { it.startsWith('services/') || it.startsWith('frontend/') || it.startsWith('jenkins/') }

          if (isJenkinsDeployCommit || !hasSourceChanges) {
            env.SKIP_PIPELINE = 'true'
            currentBuild.description = isJenkinsDeployCommit
              ? 'Skipped Jenkins deploy-tag commit'
              : 'Skipped non-source change'
          } else {
            env.SKIP_PIPELINE = 'false'
          }
        }
      }
    }

    stage('Backend Checks') {
      when {
        expression { env.SKIP_PIPELINE != 'true' }
      }
      steps {
        script {
          def services = ['auth-service', 'user-service', 'video-service', 'upload-processing-service', 'streaming-service']
          services.each { svc ->
            dir("services/${svc}") {
              sh 'npm install'
              sh 'npm run check'
            }
          }
        }
      }
    }

    stage('Build Images') {
      when {
        expression { env.SKIP_PIPELINE != 'true' }
      }
      steps {
        script {
          def services = ['auth-service', 'user-service', 'video-service', 'upload-processing-service', 'streaming-service']
          services.each { svc ->
            sh "docker build -t ${ECR_REGISTRY}/${svc}:${IMAGE_TAG} services/${svc}"
          }
        }
      }
    }

    stage('Scan Images') {
      when {
        expression { env.SKIP_PIPELINE != 'true' }
      }
      steps {
        script {
          def services = ['auth-service', 'user-service', 'video-service', 'upload-processing-service', 'streaming-service']
          services.each { svc ->
            sh "trivy image --severity HIGH,CRITICAL --exit-code 0 ${ECR_REGISTRY}/${svc}:${IMAGE_TAG}"
          }
        }
      }
    }

    stage('Push Images') {
      when {
        expression { env.SKIP_PIPELINE != 'true' }
      }
      steps {
        withCredentials([usernamePassword(
          credentialsId: 'aws-jenkins-creds',
          usernameVariable: 'AWS_ACCESS_KEY_ID',
          passwordVariable: 'AWS_SECRET_ACCESS_KEY'
        )]) {
          sh 'aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}'
        }
        script {
          def services = ['auth-service', 'user-service', 'video-service', 'upload-processing-service', 'streaming-service']
          services.each { svc ->
            sh "docker push ${ECR_REGISTRY}/${svc}:${IMAGE_TAG}"
          }
        }
      }
    }

    stage('Update Helm Values') {
      when {
        expression { env.SKIP_PIPELINE != 'true' }
      }
      steps {
        withCredentials([usernamePassword(
            credentialsId: 'github-pat',
            usernameVariable: 'GIT_USERNAME',
            passwordVariable: 'GIT_TOKEN'
        )]) {
          sh '''
          sed -i "s/tag: .*/tag: ${IMAGE_TAG}/g" helm/apps/video-streaming-platform/values-dev.yaml
          git config user.email "jenkins@example.local"
          git remote set-url origin https://${GIT_USERNAME}:${GIT_TOKEN}@github.com/AbstractLK/video-streaming-platform.git
          git config user.name "jenkins"
          git add helm/apps/video-streaming-platform/values-dev.yaml
          git diff --cached --quiet helm/apps/video-streaming-platform/values-dev.yaml || git commit -m "chore: deploy images ${IMAGE_TAG} [skip ci]"
          git push origin HEAD:${DEPLOY_BRANCH}
          '''
        }
        
      }
    }

    stage('Frontend Deploy') {
      when {
        expression { env.SKIP_PIPELINE != 'true' }
      }
      steps {
        dir('frontend') {
          sh 'npm install'
          sh 'npm run build'
        }
        withCredentials([usernamePassword(
          credentialsId: 'aws-jenkins-creds',
          usernameVariable: 'AWS_ACCESS_KEY_ID',
          passwordVariable: 'AWS_SECRET_ACCESS_KEY'
        )]) {
          sh 'aws s3 sync frontend/dist s3://${FRONTEND_BUCKET}/ --delete'
          sh 'aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths "/*"'
        }
      }
    }
  }
}
